language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

  notifications:
    email:
      recipients:
      - nik27090@mail.ru
      on_success: always # default: change
      on_failure: always # default: always