# https://docs.travis-ci.com/user/languages/java/
language: java
jdk: oraclejdk9

# Improve Build Speed https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
  - $HOME/.m2

# Notifications https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    recipients:
    - nik27090@mail.ru
    on_success: always # default: change
    on_failure: change # default: always

after_success:
- cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

# Factory line manager
  [![Travis][build-badge]][build]
  [![Coveralls][coveralls-badge]][coveralls]

  Awesome factory line manager!

  [build-badge]: https://img.shields.io/travis/nik27090/testCI/master.png?style=flat-square
  [build]: https://travis-ci.org/nik27090/testCI

  [coveralls-badge]: https://img.shields.io/coveralls/nik27090/testCI/master.png?style=flat-square
  [coveralls]: https://coveralls.io/github/nik27090/testCI